---
title: "About me"
output: 
  html_document:
    toc: FALSE
---


## Hi, I'm Amelia!

```{r, echo=FALSE, out.width='25%', fig.align='center'}
knitr::include_graphics ('profile_pic.jpg')
```

### My Background

I'm a fourth year undergraduate student studying Environmental Health Science, a field I became interested in after finding it at the intersection of public health and sustainability. My research interests include: environmental microbiology, microbial ecology, marine biology, bioremediation, microplastics, waste reduction, etc.

I became involved in research by shadowing in Dr. Erin Lipp's lab during my freshman year. Following my first year at UGA, I worked as in intern at the CDC within the Center for State, Tribal, Local, and Territorial Affairs. After being exposed to both the administrative and the research sides of public health, I realized my interests lie more on the research and applied science side; now, my goal is to attend grad school and eventually work in a government research position. 

I currently work in Dr. Lipp's lab as a student assistant performing RNA extractions and qPCR for the CEID _Wastewater Surveillance for SARS-CoV-2 in Athens, GA_ project. I generate the raw data that eventually ends up on [this website](https://www.covid19.uga.edu/wastewater-athens.html). Some awesome behind-the-scenes analysis done by the Lipp Lab (Billy Norfolk and Megan Lott) allows us to see how the total viral load of SARS-CoV-2 in wastewater correlates to daily reported cases and reflects COVID trends in the community. 

### Experience
My own independent research focuses on quantifying microplastics in the Upper Oconee Watershed by partnering with the local Upper Oconee Watershed Network to collect quarterly water samples. This is the project which prompted me to use R to perform some secondary data analyses. So far, I have used R to create simple figures such as scatterplots, box plots, and bar graphs, as well as to perform correlation matrices and generate watershed maps. 

### Course Goals
My experience in R has revolved around accomplishing a few very specific tasks, and my "workflow" usually involves a **lot** of Googling. My goals for this class are to:

1. Come away with the knowledge and skills to approach a wide set of problems and tasks using R
2. Practice a clean and organized method of performing data analyses
3. Improve my data analysis for my microplastics research project and create nice looking, publication-ready figures
4. Understand the structuring of the COVID wastewater data and get a better idea of how raw data eventually turns into the website linked above
5. Get familiar with predictive modeling/machine learning


### Hobbies & Fun Facts
- I play women's club volleyball at UGA, and I also enjoy weight lifting and biking on the Greenway!
- I'm the co-president of a club called Bag the Bag; we advocate to reduce single-use plastics (especially plastic bags), collect recycling for CHaRM, and do highway cleanups
- I expect that MADA will be one of the more rewarding classes I take at UGA, but some other fun, noteworthy ones I've taken are Scientific Diving and Ballroom Dancing!
- I love to read and I am a huge fan of public libraries - I finished 17 books this summer thanks to my PINES card! 


